### ISSUE TITLE
Documentation for new release wasn't generated

### ISSUE THREAD

**Issue by lukas-bednar** [kubevirt/api-reference#11]
there is new kubevirt release v0.3.0-alpha.0, documentation wasn't generated for this one.

**Comment by fabiand** [comment]
Maybe because it was not an annotated tag?

**Comment by lukas-bednar** [comment]
@fabiand after `v0.3.0` release is out (annotated tag), it is obvious that it didn't get generated.
I will make sure that it does.

**Comment by fabiand** [comment]
Good catch, @lukas-bednar!

**Comment by lukas-bednar** [comment]
https://travis-ci.org/kubevirt/kubevirt/builds/350727371
```
Skipping a deployment with the script provider because this branch is not permitted
```

**Comment by fabiand** [comment]
Please wait, it's still building here:
https://travis-ci.org/kubevirt/kubevirt/builds/350738276

**Comment by lukas-bednar** [comment]
Same result
```
Skipping a deployment with the script provider because this branch is not permitted
```

**Comment by rmohr** [comment]
I see it now. You will need  to add another deployment with `tag: true` instead of `branch: master`. It can have identical content if you don't need $TRAVIS_TAG to specify the version.

**Comment by rmohr** [comment]
Also see the duplication for the container deployment in `.travis.yaml`:

```yaml
- provider: script
  script: docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" && make publish
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" && make publish DOCKER_TAG=$TRAVIS_TAG
  skip_cleanup: true
  file:
  on:
    tags: true
```
